from django.urls import path
from plantaE import views
#from app1.views import *

app_main ="plantaE"

urlpatterns = [
#    path("homepage/", views.homepage, name="homepage"),
#    path('logout/', views.logout_view, name='logout'),
    path("",views.plantaEhomepage,name='plantaE_home'),
    
    path('mostrarvascula/', views.vascula_monitor, name='sensor_monitor'),
    path('exportar_excel/', views.exportar_excel, name='exportar_excel'),
    
    path('ajax/load-dataUsuario/', views.load_dataUsuario, name='load_dataUsuario'),
    path('ajax/load-dataUsuario2/', views.load_dataUsuario2, name='load_dataUsuario2'),
    path('ajax/load-dataUsuario3/', views.load_dataUsuario3, name='load_dataUsuario3'),
    path('ajax/load-dataUsuario4/', views.load_dataUsuario4, name='load_dataUsuario4'),
    path('ajax/load-dataUsuario5/', views.load_dataUsuario5, name='load_dataUsuario5'),
    path('ajax/load-dataUsuario6/', views.load_dataUsuario6, name='load_dataUsuario6'),
    path('ajax/load-dataUsuario7/', views.load_dataUsuario7, name='load_dataUsuario7'),

    path('ajax/obtener-nombre-usuario/', views.obtener_nombre_usuario, name='obtener_nombre_usuario'),
    path('ajax/obtener-fecha-invFruta/', views.obtenerfecha_invFruta, name='obtenerfecha_invFruta'),
    path('ajax/obtener-llave-recepcion/', views.obtener_llave_recepcion, name='obtener_llave_recepcion'),
    path('ajax/load-ccalidadparam/', views.load_ccalidadparam, name='load_ccalidadparam'),
    path('ajax/load-ccalidadaux/', views.ccalidad_update_aux, name='load_ccalidad_update_aux'),
    path('ajax/guardar-plantilla/', views.guardar_plantilla, name='guardar_plantilla'),
    path('ajax/guardar-plantillaRio/', views.guardar_plantillaRio, name='guardar_plantillaRio'),
    path('ajax/guardar-plantillaValle/', views.guardar_plantillaValle, name='guardar_plantillaValle'),
    path('ajax/load-inventarioProdparam/', views.load_inventarioProdparam, name='load_inventarioProdparam'),
    path("pesos",views.pesos_list,name='pesos_list'),
    path('pesos/<int:pk>/', views.pesos_detail, name='pesos_detail'),
    path('pesos/<int:pk>/delete/', views.pesos_delete, name='pesos_delete'),

    path('salidasFruta/<int:pk>/', views.article_detail, name='salidasFruta_detail'),
    path('salidasFruta2/<int:pk>/', views.salidasFruta_detail2, name='salidasFruta_detail2'),
    path("salidasFruta/cuadre",views.cuadrar_RioDia,name='salidasFruta_cuadre'),
    path("salidasFruta/cuadreValle",views.cuadrar_ValleDia,name='salidasFruta_cuadreValle'),
    path("salidasFrutaView",views.salidasFruta_list,name='salidasFruta_list2'),
    path("salidasFruta",views.article_list,name='salidasFruta_list'),
    path("salidasFrutaValle",views.article_listValle,name='salidasFruta_listValle'),
    path('ajax/get_correos/', views.get_correos_por_encargado, name='get_correos_por_encargado'),
    path('salidasFruta2/new/', views.article_create, name='salidasFruta_create2'),
    path('salidasFruta/new/', views.article_formPlantilla, name='salidasFruta_create'),
    path('salidasFruta/new/plantilla', views.article_create_plantilla, name='salidasFruta_create_plantilla'),
    path('salidasFruta/new/plantillaValle', views.article_create_plantillaValle, name='salidasFruta_create_plantillaValle'),
    path('salidasFruta/<int:pk>/edit/', views.article_update, name='salidasFruta_update'),
    path('salidasFruta/<int:pk>/delete/', views.article_delete, name='salidasFruta_delete'),
    path('salidasFruta2/<int:pk>/delete/', views.article_delete2, name='salidasFruta_delete2'),
    path('salidasFruta/<int:pk>/delete/Valle', views.article_deleteValle, name='salidasFruta_deleteValle'),
    path('salidasFruta/consultaaprovechamientos', views.poraprovechamientos, name='salidasFruta_aprovechamietos'),

    path("acumFrutaView",views.acumFruta_list2,name='acumFruta_list2'),
    path("acumFruta",views.acumFruta_list,name='acumFruta_list'),
    path("acumFruta/Valle",views.acumFruta_list,name='acumFruta_listValle'),
    path('acumFruta/<int:pk>/', views.acumFruta_detail, name='acumFruta_detail'),
    path('acumFruta2/<int:pk>/', views.acumFruta_detail2, name='acumFruta_detail2'),
    path('acumFruta/new/', views.acumFruta_create, name='acumFruta_create'),
    path('acumFruta/<int:pk>/edit/', views.acumFruta_update, name='acumFruta_update'),
    path('acumFruta/<int:pk>/delete/', views.acumFruta_delete, name='acumFruta_delete'),
    path('acumFruta2/<int:pk>/delete/', views.acumFruta_delete2, name='acumFruta_delete2'),
    path('acumFruta/consulta/', views.acumFruta_consulta, name='acumFruta_consulta'),
    path('acumFruta/consultaValle/', views.acumFruta_consultaValle, name='acumFruta_consultaValle'),
    path('recepcionesFruta/<int:pk>/edit/', views.recepciones_update, name='recepcionesFruta_update'),
    path("recepcionesFruta/process",views.procesarrecepcion,name='recepcionesFruta_process'),
    path("inventarioProd/process/",views.procesarinvprodconten,name='inventarioProd_contprocess'),
    path("inventarioProd/processv2/",views.procesarinvprodcontenv2,name='inventarioProd_contprocessv2'),
    path("recepcionesFruta",views.recepciones_list,name='recepcionesFruta_list'),
    path('recepcionesFruta/<int:pk>/delete/', views.recepcionesFruta_delete, name='recepcionesFruta_delete'),
    path('recepcionesFruta/<int:pk>/', views.recepciones_detail, name='recepcionesFruta_detail'),
    path("recepcionesFruta/reporteAcum",views.recepciones_reporteAcum,name='recepcionesFruta_reporteAcum'),
    path("recepcionesFruta/reporteAcumKgm2Orden",views.recepciones_reporteAcumKgm2Orden,name='recepcionesFruta_reporteAcumKgm2Orden'),
    path("recepcionesFruta/reporteAcumKgm2Estruc",views.recepciones_reporteAcumKgm2Estruc,name='recepcionesFruta_reporteAcumKgm2Estruc'),  
    path("recepcionesFruta/reporteAcumKgm2Variedad",views.recepciones_reporteAcumKgm2Variedad,name='recepcionesFruta_reporteAcumKgm2Variedad'),
    path("salidasFrutaPublic/reporteAcum/semanal",views.recepciones_reporteAcumSemPublic,name='salidasFrutaPublic_reporteAcumSem'),
    path("recepcionesFruta/reporteAcum/semanal",views.recepciones_reporteAcumSem,name='recepcionesFruta_reporteAcumSem'),
    path("recepcionesFruta/reporteAcum/grafico",views.recepciones_reportecurva,name='recepcionesFruta_reportecurva'),
    path("salidasFrutaPublic/graficoPublic",views.recepciones_reportecurva2,name='recepcionesFruta_reportecurva2'),
    path("recepcionesFruta/reporteAcum/loadgrafico",views.graficas,name='load_grafico'),
    path("boletasFruta",views.boletas_list,name='boletasFruta_list'),
    path("boletasFruta/reporterecepcion",views.boletas_reporterecepcion,name='boletasFruta_reporterecepcion'),
    path("boletasFruta/reportetraza",views.boletas_reportetraza,name='boletasFruta_reportetraza'),
    path("boletasFruta/reportetrazaexpo",views.boletas_reportetrazaexpo,name='boletasFruta_reportetrazaexpo'),
    path("boletasFruta/trazarecepcion",views.boletas_trazarecepcion,name='boletasFruta_trazarecepcion'),
    path("boletasFruta/constanciatrazarecepcion",views.boletas_constanciatrazarecepcion,name='boletasFruta_constanciatrazarecepcion'),
    path("boletasFruta/constanciatraza",views.boletas_constanciatraza,name='boletasFruta_constanciatraza'),
    path("boletasFruta/constanciarecepcion",views.boletas_constanciarecepcion,name='boletasFruta_constanciarecepcion'),
    path('boletasFruta/<int:pk>/edit/', views.boletas_update, name='boletas_update'),
    path('boletasFruta/<int:pk>/', views.boletas_detail, name='boletas_detail'),
    path('boletasFruta/<int:pk>/delete/', views.boletas_delete, name='boletas_delete'),
    path("ccalidad",views.ccalidad_list,name='ccalidad_list'),
    path('ccalidad/<int:pk>/', views.ccalidad_detail, name='ccalidad_detail'),
    path('ccalidad/new/', views.ccalidad_create, name='ccalidad_create'),
    path('ccalidad/<int:pk>/edit/', views.ccalidad_update, name='ccalidad_update'),
    path('ccalidad/<int:pk>/delete/', views.ccalidad_delete, name='ccalidad_delete'),
    path("envioslocal",views.envioslocal_list,name='envioslocal_list'),
    path('envioslocal/<int:pk>/delete/', views.envioslocal_delete, name='envioslocal_delete'),
    path('envioslocal/<int:pk>/', views.envioslocal_detail, name='envioslocal_detail'),
    path("inventarioProd/plantilla",views.inventarioProd_grabarplantilla,name='inventarioProd_grabar'),
    path("inventarioProd",views.inventarioProd_list,name='inventarioProd_list'),
    path('inventarioProd/<int:pk>/', views.inventarioProd_detail, name='inventarioProd_detail'),
    path('inventarioProd/new/', views.inventarioProd_create, name='inventarioProd_create'),
    path('inventarioProd/<int:pk>/edit/', views.inventarioProd_update, name='inventarioProd_update'),
    path('inventarioProd/<int:pk>/delete/', views.inventarioProd_delete, name='inventarioProd_delete'),
    path("inventarioProd/cargacontenedor",views.cargacontenedores_list,name='inventarioProd_contenlist'),
    path("inventarioProd/cargacontenedorv2",views.cargacontenedores_listv2,name='inventarioProd_contenlistv2'),
    path("inventarioProd/packinglist",views.contenedorpacking_list,name='inventarioProd_packinglist'),
    path("inventarioProd/packinglist_detail",views.contenedorpacking_list_detail,name='inventarioProd_packinglist_detail'),
    path('inventarioProd/packinglist_detail/<int:pk>/edit/', views.packinglist_update, name='inventarioProd_packinglist_update'),
    path('inventarioProd/packinglist_detail/<int:pk>/delete/', views.packinglist_delete, name='inventarioProd_packinglist_delete'),
    path("inventarioProd/inventariogeneral",views.inventariogeneral_list,name='inventarioProd_inventariogeneral'),
    path("inventarioProd/inventariogeneralfruta",views.inventariogeneralfruta_list,name='inventarioProd_inventariogeneralfruta'),
    path("inventarioProd/aprovechamientos",views.aprovechamientos,name='inventarioProd_aprovechamientos'),
    path('inventarioProd/reporteInv', views.reporteInventario, name='reporte_inventario'),
    path('inventarioProd/validaroventa', views.validaroventa, name='inventarioProd_validaroventa'),
    path('ajax/load-contenedores/', views.load_contenedores, name='load_contenedores'),
    path("contenedores",views.contenedores_list,name='contenedores_list'),
    path('contenedores/new/', views.contenedores_create, name='contenedores_create'),
    path('contenedores/<int:pk>/edit/', views.contenedores_update, name='contenedores_update'),
    path('contenedores/<int:pk>/delete/', views.contenedores_delete, name='contenedores_delete'),
    path("items",views.items_list,name='items_list'),
    path('items/new/', views.items_create, name='items_create'),
    path('items/<int:pk>/edit/', views.items_update, name='items_update'),
    path('items/<int:pk>/delete/', views.items_delete, name='items_delete'),
    path('generate_packing_list_pdf/', views.generate_packing_list_pdf, name='generate_packing_list_pdf'),
    path('escanearbarras/', views.escanearbarras, name='escanearbarras'),
    path('dashboard/', views.dashboard_acumfruta, name='dashboard_acumfruta'),
    path('dashboard/tecnicos', views.dashboard_tecnicos, name='dashboard_acumfruta2'),
    path('api/ordenes/', views.get_ordenes_por_finca, name='api_ordenes_por_finca'),
    path('api/estructuras/', views.get_estructuras_por_orden, name='api_estructuras_por_orden'),
    path('api/variedad/', views.get_variedades_por_estructura, name='api_variedades_por_estructura'),

    
    path('api/ordenes2/', views.get_ordenes_por_finca2, name='api_ordenes_por_finca2'),
    path('api/estructuras2/', views.get_estructuras_por_orden2, name='api_estructuras_por_orden2'),
    path('api/variedad2/', views.get_variedades_por_estructura2, name='api_variedades_por_estructura2'),
    
    path('reporte-pivote/tecnicos', views.reporte_tabla_pivote2, name='reporte_tabla_pivote2'),
    path('reporte-pivote/', views.reporte_tabla_pivote, name='reporte_tabla_pivote'),

    path("itemsenvios",views.itemsenvios_list,name='itemsenvios_list'),
    path('itemsenvios/new/', views.itemsenvios_create, name='itemsenvios_create'),
    path('itemsenvios/<int:pk>/edit/', views.itemsenvios_update, name='itemsenvios_update'),
    path('itemsenvios/<int:pk>/delete/', views.itemsenvios_delete, name='itemsenvios_delete'),
]
