from .boletas_views import *
from .recepciones_views import *
from .actpeso_views import *
from .itemsenvios_views import *
from .itemsprodterm_views import *
from .itemsprodtermaux_views import *
from .ccalidad_views import *
from .envioslocal_views import *
from .contenedores_views import *
from .controlcajas_views import *
from .pedidoscarreta_views import *
from .supervisioncultivos_views import *
from .salidasfruta_views import *
from .inventarioprodterm_views import *
from .cargacontenedor_views import *
from .acumfruta_views import *
from .reportegerencial_views import *
from .reportetecnicos_views import *
from .supervisionfito_views import *
from .home_views import *