from .boletas_views import *
from .recepciones_views import *
from .actpeso_views import *
from .itemsenvios_views import *
from .itemsprodterm_views import *
from .ccalidad_views import *
from .envioslocal_views import *
from .contenedores_views import *
from .controlcajas_views import *
from .pedidoscarreta_views import *
from .supervisioncultivos_views import *
from .salidasFruta_views import *