# Generated by Django 4.1 on 2024-01-10 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='TCategorias',
            fields=[
                ('categoría_código', models.BigAutoField(db_column='Categoría_Código', primary_key=True, serialize=False)),
                ('categoría_centro', models.CharField(blank=True, db_column='Categoría_Centro', max_length=15, null=True)),
            ],
            options={
                'db_table': 't_categorias',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TCentros',
            fields=[
                ('centro', models.CharField(db_column='Centro', max_length=15, primary_key=True, serialize=False)),
                ('descripción', models.CharField(blank=True, db_column='Descripción', max_length=125, null=True)),
                ('responsable', models.CharField(blank=True, db_column='Responsable', max_length=50, null=True)),
                ('area_field', models.FloatField(blank=True, db_column='Area_', null=True)),
            ],
            options={
                'db_table': 't_centros',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TDespachos',
            fields=[
                ('pedido', models.BigAutoField(db_column='Pedido', primary_key=True, serialize=False)),
                ('mtemporal', models.DateTimeField(blank=True, db_column='mTemporal', null=True)),
                ('fecha', models.DateField(blank=True, db_column='Fecha', null=True)),
                ('envio', models.BigIntegerField(blank=True, db_column='Envio', null=True)),
                ('origen', models.CharField(blank=True, db_column='Origen', max_length=50, null=True)),
                ('rubro', models.CharField(blank=True, db_column='Rubro', max_length=15, null=True)),
                ('citem', models.CharField(blank=True, db_column='cItem', max_length=15, null=True)),
                ('cantidad', models.FloatField(blank=True, null=True)),
                ('ccentro', models.CharField(blank=True, db_column='cCentro', max_length=15, null=True)),
            ],
            options={
                'db_table': 't_despachos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TItems',
            fields=[
                ('código_articulo', models.CharField(db_column='Código_Articulo', max_length=15, primary_key=True, serialize=False)),
                ('artículo', models.CharField(blank=True, db_column='Artículo', max_length=125, null=True)),
                ('unidad_medida', models.CharField(blank=True, db_column='Unidad_Medida', max_length=15, null=True)),
            ],
            options={
                'db_table': 't_items',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Items',
        ),
    ]
